Fix build errors missing podman/docker module
Example:
Traceback (most recent call last):
  File "/home/ubuntu/kolla/kolla/image/build.py", line 79, in run
    task.run()
  File "/home/ubuntu/kolla/kolla/image/tasks.py", line 144, in run
    self.builder(self.image)
  File "/home/ubuntu/kolla/kolla/image/tasks.py", line 424, in builder
    if isinstance(e, podman.errors.exceptions.BuildError):
NameError: name 'podman' is not defined

Change-Id: I947c77750b3ccfb975e010c2042a3716e3e46bde