Fix lower-constraints and kolla CI jobs
Multiple fixes to fix multiple problems.

1. Bump setuptools requirement to 21.0.0

The 16.0.0 requirement breaks the lower-constraints job on Ubuntu
bionic. We see the following error:

AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

2. ubuntu-binary horizon image needs to use python3 for django
manage.py

3. ubuntu-binary nova-placement-api image needs to use python3 for
apache mod wsgi.

4. nova-libvirt needs exact qemu dependencies due to packaging change

5. OracleLinux repos definition was changed in official image.

6. Fetch InfluxDB gpg key for Ubuntu base image from influx server.

Change-Id: Ic797d41f53a5f146d112619f1683cbfbf3a85dc2