Fix ironic build issues - LANG related
ironic drivers-requirements installation fails with:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 2:
ordinal not in range(128)

Squashed ,,cherry-pick'' from stable/train - adding LANG block and locale-gen
for Ubuntu family in base Dockerfile:

https://review.opendev.org/#/c/684808/
https://review.opendev.org/#/c/691835/
https://review.opendev.org/#/c/694099/

Temporarily blocks bifrost building as well - to revert!

Change-Id: I79ee884ad35bf5166c9ea303d73416271ff5f637
(cherry picked from commit 3c435cb0781b343ad7f7223609cf2eefb2f8738a)