build: remove link to failed log before creating
Kolla allows to create separate logs per image. It also makes very
useful symlinks to those builds which fail.

But it fails to do that on next builds:

ERROR:kolla.common.utils:aodh-base Failed with status: error
Traceback (most recent call last):
  File "./tools/build.py", line 40, in <module>
    sys.exit(main())
  File "./tools/build.py", line 30, in main
    statuses = build.run_build()
  File "/home/hrw/devel/kolla/kolla/image/build.py", line 1333, in run_build
    results = kolla.summary()
  File "/home/hrw/devel/kolla/kolla/image/build.py", line 1037, in summary
    "000_FAILED_%s.log" % name))
FileExistsError: [Errno 17] File exists: 'aodh-base.log' -> 'logs/debian-source-buster/000_FAILED_aodh-base.log'

Change-Id: I85132bbace63c8b386f69ddb758a3b52e52c0ef0
(cherry picked from commit 5792c1d7b44737f1f39bb1a81b0c95207ad087ad)