Fix multiple issues
Multiple issues combined to pass CI

1. drop tripleo-common-tempest-plugin

This is not needed plugin without any branches or releases. And wants Python 3
while we have Py2 for CentOS 7.

Original Change-Id: I9cab91b82941ea125b16d19e68722ce41a1f11f2
14:41 < hrw> is  tripleo-common-tempest-plugin your stuff?
14:43 <@EmilienM> yes and it does nothing. I thought we removed that?
14:43 <@EmilienM> apparently it's still here https://github.com/openstack/tripleo-common-tempest-plugin
14:43 <@EmilienM> we should burn it, weshay|ruck ^
14:44 < hrw> EmilienM: also fine to drop from train?
14:44 <@EmilienM> burn it everywhere you can
14:44 < hrw> THANKS
14:44 <@EmilienM> it has never been useful
14:44 <@EmilienM> and people who started it left
14:48 <@weshay|ruck> EmilienM, yup

2. Sensu: Remove ceph and process-checks plugins from client

The sensu image became unbuildable, failing to install the ceph plugin:

    Unable to resolve dependencies: sensu-plugins-ceph requires english (= 0.6.3)

This has happened because the author of the 'english' gem has seen fit
to publish a new 0.7.0 release, and 'yank' [1] all previous releases
from rubygems.

This change removes the ceph and process-checks plugins, which both
suffer from a dependency on the yanked english 0.6.3.

[1] https://rubygems.org/gems/english/versions/0.6.3

Original Change-Id: I9d34413fa10b5a2920aca60b08141bfaddcc7415
Closes-Bug: #1871600
(cherry picked from commit 818dc4d6ff12a3119be072e0c68e2d2c8da9b799)
(cherry picked from commit 2d1017be3fd658011fc5a86bd38b7265da306ea3)

3. Use freezer queens releases

There are no freezer releases in Rocky, so these packages stayed on
master. This is now python 3 only, so fails to build. Pin to Queens
6.0.0 releases.

4. Pin elasticsearch gem to <7.6.0 in fluentd

Since the release of the elasticsearch 7.6.0 gem, the fluentd image
fails to build on Ubuntu due to a transitive dependency on faraday.

ERROR:  Error installing fluent-plugin-elasticsearch:
    faraday requires Ruby version >= 2.3.

Pin elasticsearch to <7.6.0.

Change-Id: I6200ed527244313107666753257f52d4b9305dd3