utils: be Python 2 compatible when squashing is enabled
INFO:kolla.common.utils.base:Parent lastest layer is: sha256:75835a67d1341bdc7f4cc4ed9fa1631a7d7b6998e9327272afea342d90c4ab6d
ERROR:kolla.common.utils.base:Unknown error when building
Traceback (most recent call last):
File "/home/hrw/devel/linaro/17.12/kolla/kolla/image/build.py", line 598, in builder
    self.squash()
  File "/home/hrw/devel/linaro/17.12/kolla/kolla/image/build.py", line 619, in squash
    tmp_dir=self.conf.squash_tmp_dir)
  File "/home/hrw/devel/linaro/17.12/kolla/kolla/common/utils.py", line 72, in squash
    ex.stdout)
AttributeError: 'CalledProcessError' object has no attribute 'stdout'

stdout was added in Python 3 as alias for output

Change-Id: I7a6cef2ef6201d6b34c640bd6d1c7762c8bf5611