kolla-toolbox: limit openstacksdk to <0.18 version
Queens images limit python-openstackclient to 3.12.0 version but do not set
limits on openstacksdk package. In newest images we got openstacksdk 0.18.2
which does not work with 3.12.0 as you can see below:

()[root@7739bc780a41 /]# openstack
Traceback (most recent call last):
  File "/opt/ansible/bin/openstack", line 7, in <module>
    from openstackclient.shell import main
  File "/opt/ansible/local/lib/python2.7/site-packages/openstackclient/shell.py", line 29, in <module>
    from openstackclient.common import clientmanager
  File "/opt/ansible/local/lib/python2.7/site-packages/openstackclient/common/clientmanager.py", line 166, in <module>
    'openstack.cli.base',
  File "/opt/ansible/local/lib/python2.7/site-packages/openstackclient/common/clientmanager.py", line 137, in get_plugin_modules
    __import__(ep.module_name)
  File "/opt/ansible/local/lib/python2.7/site-packages/openstackclient/network/client.py", line 17, in <module>
    from openstack import profile
ImportError: cannot import name profile

0.17.2 works fine:

Successfully installed openstacksdk-0.17.2
()[root@7739bc780a41 /]# openstack
(openstack)

Rocky images are fine.

Change-Id: Id794040daf7d13f6d76067a4b376c45488eadf7e