gnocchi: install missing python3-wheel package
When there is no cradox wheel available on pypi (for non-x86 archs) then
build fails:

Step 5/8 : RUN pip3 --no-cache-dir install --upgrade cradox     && truncate -s 0 /etc/apache2/ports.conf
 ---> Running in 3a850b4d6319
Collecting cradox
  Downloading https://files.pythonhosted.org/packages/30/a8/f4790a3f5af7c7616dda7bd5cddbe31d3cf7c35319b700ff49e14ffa8153/cradox-2.1.2.tar.gz (44kB)
    Complete output from command python setup.py egg_info:
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    ERROR: Failed to build one or more wheels

Change-Id: I519c2a59208376ae05e0a6f5fa4de303670f2674