CI: Install python deps, fix mod_wsgi in cyborg-api, disable masakari-monitors
setuptools is missing from infra image - so it needs to be installed.

Copy cat of a kolla-ansible change: https://review.opendev.org/#/c/735808/

Fixes also cyborg-api to use py3 mod_wsgi in centos8

Temporarily disables masakari-monitors build, because it fails on centos8
due to problems with libvirt-python===5.7.0 (upper-constraints):

Missing type converters:
virTypedParameterPtr:1
ERROR: failed virConnectSetIdentity

Depends-On: https://review.opendev.org/#/c/736744/
Change-Id: I6068abcbc0e73eeab77b0aa99983a95adc6defd3