monasca, tempest: install librdkafka-dev to get it built for non-x86/source
fixes build issue under Debian:buster on AArch64:

In file included from confluent_kafka/src/confluent_kafka.c:17:
confluent_kafka/src/confluent_kafka.h:22:10: fatal error: librdkafka/rdkafka.h: No such file or directory
 #include <librdkafka/rdkafka.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

Under Ubuntu it is still broken because librdkafka is too old.

Change-Id: I1e54645ea5805f985c9bd04f9936ea3edbebfd31