Fix l3_agent.ini rendering error when DVR
The if/else blocks in this file cause a rendering error on control nodes
when enable_neutron_dvr: yes

ParsingError: File contains parsing errors: <???>
        [line  3]: u'    external_network_bridge =\n'

Change-Id: Ia461dcbbec531c4c6295b3c7e10da12c57b7d58b
Closes-Bug: 1626995