Fix UnicodeEncodeError for Manila
TASK: [manila | Copying over manila.conf] fails while
deploying Manila ubuntu binary image with the following
error.

UnicodeEncodeError: 'ascii' codec can't encode character
u'\u2018' in position 313: ordinal not in range(128)

The reason was use of non-ascii character <``> in manila.conf.j2
which is replaced by <''> in this patch to fix the issue.

Change-Id: Ic26a5829ed700179997c7c06836fd581a67a6777