Restore use of contextfunction decorator
This code supporting Jinja2<3 was originally using the contextfunction
decorator rather than contextfilter. Although they are both replaced by
pass_context, the old decorators are different.

This resolves the following issue seen in kayobe CI:

    TypeError: handle_repos() missing 1 required positional argument: 'mode'

This was only noticed with kayobe because it uses upper constraints to
install kolla.

Change-Id: Ie4bccb9ed3f4d8782730c5929abbfa73da215a8c