Add ssh-keyscan to unblock kolla gate
As a change to remove puppet from infra nodepool,
ssh-keyscan is needed for each node [0]

Permissions to ssh/config file should be 600 instead
of current 664 [1]

Fix unit tests for missing fedora:
ValueError: Valid values are [centos, rhel, ubuntu, oraclelinux, debian], but found 'fedora'

Refs:
[0] http://lists.openstack.org/pipermail/openstack-dev/2017-April/116036.html
[1] http://logs.openstack.org/68/461368/1/check/gate-kolla-ansible-dsvm-deploy-centos-binary-centos-7-nv/0a94da7/console.html#_2017-05-01_12_06_08_440775

Closes-Bug: #1687408
Change-Id: I338e457fff35d8a28bd9f96e88dbb4ee55a47864
(cherry picked from commit 508f73e059fdfe8e051c58762dc8e21d826d54db)