Fix build of masakari-monitors image
The CentOS 8 Advanced Virtualization repository recently added libvirt
7.0.0. The current version of libvirt-python fails to build against it:

    running build
    /usr/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
    /var/lib/kolla/venv/bin/python3.6 generator.py libvirt /usr/share/libvirt/api/libvirt-api.xml
    Found 480 functions in /usr/share/libvirt/api/libvirt-api.xml
    Found 0 functions in libvirt-override-api.xml
    Generated 389 wrapper functions
    Missing type converters:
    char ** *:1
    char **:1
    ERROR: failed virDomainAuthorizedSSHKeysGet
    ERROR: failed virDomainAuthorizedSSHKeysSet
    error: command '/var/lib/kolla/venv/bin/python3.6' failed with exit status 1

We need at least libvirt-python v6.10.0.

Change-Id: If69536387513ca221e03a80878016532a41aef87