elasticsearch: install Java first on CentOS too
elasticsearch-oss package fails to install if we install it with Java:

INFO:kolla.common.utils.elasticsearch:could not find java; set JAVA_HOME
INFO:kolla.common.utils.elasticsearch:error: %prein(elasticsearch-oss-0:6.8.23-1.noarch) scriptlet failed, exit status 1
INFO:kolla.common.utils.elasticsearch:[91mError in PREIN scriptlet in rpm package elasticsearch-oss

Backport down to ussuri needed.

This change also includes a backport of
I7d4788f5b63fba24e3b2f9b15c16866ff811d83e:

Always use the distro-provided libvirt-python

This patch switches masakari-monitors image to follow nova-compute
and ceilometer-compute images.
This will be used and required after [1] merges.
Usage of libvirt-python from PyPI has already proven to be
problematic on CentOS Stream in our stable branches. [2]
With this patch we avoid those issues as well.

[1] https://review.opendev.org/c/openstack/masakari-monitors/+/804913
[2] https://review.opendev.org/c/openstack/kolla/+/797102

Depends-On: https://review.opendev.org/c/openstack/masakari-monitors/+/804913

NOTE(hrw): added removal of libvirt-python from upper-constraints as we have
never version of libvirt that Victoria used.

This change also includes a backport of
I5efab66e487e06abd1a56af97d7e7caa1ebc880d:

Use jinja2.pass_context instead of contextfilter

The contextfilter decorator was deprecated in jinja2 3.0.0, and has been
dropped in 3.1.0. This results in the following warning, and failed
attempts to use filters:

    [WARNING]: Skipping plugin (filters.py) as it seems to be invalid:
    module 'jinja2' has no attribute 'contextfilter'

This change switches to use the pass_context decorator. The minimum
version of Jinja2 is raised to 3 to ensure pass_context is present.

This change has been updated to also support Jinja2 2.x releases,
since the Wallaby upper constraints specify 2.11.3. In practice, most
users will not use UC to install kolla.

CoAuthored-by: Mark Goddard <mark@stackhpc.com>

Finally, amended for Debian Buster to also skip the lower
constraint from masakari-monitors.

Finally, finally, includes also hotfix for contextfunction.
Ie4bccb9ed3f4d8782730c5929abbfa73da215a8c

Change-Id: I72d7920acd8d15941c8c57a4186186212b273a38
(cherry picked from commit 976465c448c4de2bd323021b946770b26ab1e912)